from tools.environment import *
from task.genshin.genshin import Genshin


class Fontaine(Genshin):
    # 悬铃木
    def mallow(self):
        self.indicate("采集：悬铃木×9，椴木×3")
        self.home()
        self.open_sub("冒险之证")
        click(300, 440)
        wait(800)
        click(537, 296)
        wait(800)
        self.tp_domain("罪祸的终末")
        wait(800)
        click(1682, 1008)
        self.world()
        keydown("S")
        wait(10000)
        keyup("S")
        wait(300)
        keydown("D")
        wait(300)
        keyup("D")
        wait(300)
        keydown("S")
        wait(2000)
        keyup("S")
        wait(300)
        keydown("A")
        wait(1000)
        keyup("A")
        wait(500)
        press("Z")
        wait(500)

    # 炬木
    def torch(self):
        self.indicate("采集：炬木×15")
        self.home()
        self.open_sub("冒险之证")
        click(300, 440)
        wait(800)
        click(537, 296)
        wait(800)
        self.tp_domain("苍白的遗荣")
        click(545, 1000)
        wait(800)
        self.tp_point(1)
        keydown("A")
        wait(3300)
        keyup("A")
        wait(500)
        keydown("W")
        wait(3000)
        keyup("W")
        wait(500)
        keydown("A")
        wait(1200)
        keyup("A")
        wait(500)
        press("Z")
        wait(500)

    # 白梣木
    def ash(self):
        self.indicate("采集：白梣木×12")
        self.home()
        self.open_sub("冒险之证")
        click(300, 440)
        wait(800)
        click(537, 296)
        wait(800)
        self.tp_domain("苍白的遗荣")
        click(522, 808)
        wait(800)
        self.tp_point(2)
        keydown("S")
        wait(8000)
        keyup("S")
        wait(500)
        keydown("A")
        wait(7000)
        keyup("A")
        wait(500)
        keydown("W")
        wait(3400)
        keyup("W")
        wait(500)
        keydown("A")
        wait(4700)
        keyup("A")
        wait(500)
        press("Z")
        wait(500)

    # 椴木
    def linden(self):
        self.indicate("采集：椴木×9")
        self.home()
        self.open_sub("冒险之证")
        click(300, 440)
        wait(800)
        click(537, 296)
        wait(800)
        self.tp_domain("罪祸的终末")
        wait(800)
        click(1682, 1008)
        self.world()
        keydown("S")
        wait(2500)
        keyup("S")
        wait(500)
        keydown("A")
        wait(2500)
        keyup("A")
        wait(300)
        keydown("W")
        wait(11800)
        keyup("W")
        wait(300)
        keydown("A")
        wait(100)
        keyup("A")
        wait(300)
        press("Z")
        wait(500)

    # 香柏木
    def cypress(self):
        self.indicate("采集：香柏木×15")
        self.home()
        self.open_sub("冒险之证")
        click(300, 440)
        wait(800)
        click(537, 296)
        wait(800)
        self.tp_domain("罪祸的终末")
        click(1213, 201)
        wait(800)
        self.tp_point(0)
        keydown("S")
        wait(4000)
        keyup("S")
        wait(500)
        keydown("D")
        wait(6000)
        keyup("D")
        wait(500)
        keydown("W")
        wait(3000)
        keyup("W")
        wait(500)
        keydown("D")
        wait(3600)
        keyup("D")
        wait(500)
        keydown("W")
        wait(2100)
        keyup("W")
        wait(500)
        press("Z")
        wait(500)