from tools.environment import *
from task.genshin.genshin import Genshin


class Inazuma(Genshin):
    # 御伽木
    def otogi(self):
        self.indicate("采集：御伽木×12")
        self.home()
        self.open_sub("冒险之证")
        click(300, 440)
        wait(800)
        click(537, 296)
        wait(800)
        self.tp_domain("椛染之庭")
        click(824, 311)
        wait(800)
        self.tp_point(0)
        keydown("A")
        wait(9700)
        keyup("A")
        wait(300)
        keydown("W")
        wait(1100)
        keyup("W")
        wait(300)
        press("Z")
        wait(300)

    # 孔雀木&御伽木
    def aralia_otogi(self):
        self.indicate("采集：孔雀木×18 御伽木×3")
        self.home()
        self.open_sub("冒险之证")
        click(300, 440)
        wait(800)
        click(537, 296)
        wait(800)
        self.tp_domain("砂流之庭")
        click(978, 845)
        wait(800)
        self.tp_point(0)
        keydown("A")
        wait(4200)
        keyup("A")
        wait(300)
        press("Z")
        wait(300)
        keydown("A")
        wait(300)
        keyup("A")
        wait(300)
        keydown("S")
        wait(2700)
        keyup("S")
        wait(300)
        keydown("D")
        wait(500)
        keyup("D")
        wait(11800)
        press("Z")
        wait(300)

    # 枫木
    def maple(self):
        self.indicate("采集：枫木×12")
        self.home()
        self.open_sub("冒险之证")
        click(300, 440)
        wait(800)
        click(537, 296)
        wait(800)
        self.tp_domain("砂流之庭")
        click(566, 555)
        wait(800)
        self.tp_point(2)
        keydown("A")
        wait(1000)
        keyup("A")
        wait(300)
        keydown("W")
        wait(1400)
        keyup("W")
        wait(300)
        press("Z")
        wait(300)
        keydown("D")
        wait(5300)
        keyup("D")
        wait(300)
        keydown("W")
        wait(4000)
        keyup("W")
        wait(6300)
        press("Z")
        wait(300)
        keydown("D")
        wait(3000)
        keyup("D")
        wait(12800)
        press("Z")
        wait(300)
        keydown("W")
        wait(5800)
        keyup("W")
        wait(9800)
        press("Z")
        wait(300)

    # 梦见木
    def yumemiru(self):
        self.indicate("采集：梦见木×12")
        self.home()
        self.open_sub("冒险之证")
        click(300, 440)
        wait(800)
        click(537, 296)
        wait(800)
        self.tp_domain("砂流之庭")
        click(937, 617)
        wait(800)
        self.tp_point(0)
        keydown("S")
        wait(1300)
        keyup("S")
        wait(500)
        keydown("A")
        wait(400)
        keyup("A")
        wait(300)
        press("Z")
        wait(300)
        keydown("W")
        wait(500)
        keyup("W")
        wait(500)
        keydown("D")
        wait(2200)
        keyup("D")
        wait(500)
        keydown("W")
        wait(1000)
        keyup("W")
        wait(300)
        keydown("D")
        wait(800)
        keyup("D")
        wait(300)
        keydown("W")
        wait(500)
        keyup("W")
        wait(9000)
        press("Z")
        wait(500)

